[{
    "link": "/login",
    "title": "로그인",
    "type": "form",
    "displayOrder": 1,
    "components": [{
        "name": "userId",
        "label": "userId",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "password",
        "label": "password",
        "type": "password",
        "options": [],
        "value": "1111",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "locale",
        "label": "locale",
        "type": "select",
        "options": ["ko:KO", "en:EN", "de:DE", "fr:FR", "es:ES", "cs:CZ"],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 3
    }]
}, {
    "link": "/join",
    "title": "회원가입",
    "type": "form",
    "displayOrder": 2,
    "components": [{
        "name": "userId",
        "label": "아이디",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": -2
    }, {
        "name": "userName",
        "label": "이름",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": -1
    }, {
        "name": "password",
        "label": "비밀번호",
        "type": "password",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "repassword",
        "label": "비밀번호 확인",
        "type": "password",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 3
    }, {
        "name": "type",
        "label": "사용자 종류",
        "type": "radio",
        "options": ["customer:손님", "designer:디자이너", "staff:스탭", "manager:매니저"],
        "value": "1",
        "format": "",
        "role": ["all"],
        "displayOrder": 4
    }, {
        "name": "fileId",
        "label": "fileId",
        "type": "hidden",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 5
    }, {
        "name": "userEmail",
        "label": "이메일",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 7
    }, {
        "name": "mail",
        "label": "mail",
        "type": "select",
        "options": [":직접선택", "gmail.com:구글", "naver.com:네이버", "nate.com:네이트", "daum.com:다음"],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 8
    }, {
        "name": "userPhone",
        "label": "핸드폰",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 9
    }, {
        "name": "userGrade",
        "label": "등급",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 10
    }, {
        "name": "userProfile",
        "label": "프로필정보",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 11
    }, {
        "name": "status",
        "label": "status",
        "type": "hidden",
        "options": [],
        "value": "join",
        "format": "",
        "role": ["all"],
        "displayOrder": 14
    }]
}, {
    "link": "/coupon",
    "title": "쿠폰등록",
    "type": "form",
    "displayOrder": 2,
    "components": [{
        "name": "name",
        "label": "쿠폰명",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "description",
        "label": "description",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "info",
        "label": "info",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 3
    }, {
        "name": "fileId",
        "label": "fileId",
        "type": "hidden",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 4
    }, {
        "name": "startDate",
        "label": "유효간",
        "type": "date",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 5
    }, {
        "name": "endDate",
        "label": "~",
        "type": "date",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 6
    }]
}, {
    "link": "/group",
    "title": "그룹등록",
    "type": "form",
    "displayOrder": 2,
    "components": [{
        "name": "name",
        "label": "그룹명",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "type",
        "label": "그룹 종류",
        "type": "radio",
        "options": ["guest:손님", "admin:관리자", "user:사용자"],
        "value": "0",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "startDate",
        "label": "유효간",
        "type": "date",
        "options": [],
        "value": "",
        "format": "yyyy-mm-dd",
        "role": ["all"],
        "displayOrder": 3
    }, {
        "name": "endDate",
        "label": "~",
        "type": "date",
        "options": [],
        "value": "",
        "format": "yyyy-mm-dd",
        "role": ["all"],
        "displayOrder": 4
    }]
}, {
    "link": "/style",
    "title": "스타일등록",
    "type": "form",
    "displayOrder": 2,
    "components": [{
        "name": "name",
        "label": "스타일명",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "description",
        "label": "description",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "fileId",
        "label": "fileId",
        "type": "hidden",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 3
    }]
}, {
    "link": "/board",
    "title": "게시판",
    "type": "form",
    "displayOrder": 3,
    "components": [{
        "name": "id",
        "label": "id",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "title",
        "label": "title",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "description",
        "label": "description",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 3
    }, {
        "name": "fileId",
        "label": "fileId",
        "type": "file",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 4
    }]
}, {
    "link": "/groupList",
    "title": "그룹목록",
    "type": "form",
    "displayOrder": 99,
    "components": [{
        "name": "name",
        "label": "그룹명",
        "type": "input",
        "options": [],
        "value": "",
        "format": "",
        "role": ["all"],
        "displayOrder": 1
    }, {
        "name": "type",
        "label": "그룹 종류",
        "type": "radio",
        "options": ["guest:손님", "admin:관리자", "user:사용자"],
        "value": "0",
        "format": "",
        "role": ["all"],
        "displayOrder": 2
    }, {
        "name": "startDate",
        "label": "유효간",
        "type": "date",
        "options": [],
        "value": "",
        "format": "yyyy-mm-dd",
        "role": ["all"],
        "displayOrder": 3
    }, {
        "name": "endDate",
        "label": "~",
        "type": "date",
        "options": [],
        "value": "",
        "format": "yyyy-mm-dd",
        "role": ["all"],
        "displayOrder": 4
    }]
}, {
    "link": "/contract",
    "title": "계약",
    "type": "form",
    "displayOrder": 2147483646,
    "components": []
}, {"link": "/logout", "title": "로그아웃", "type": "form", "displayOrder": 2147483647, "components": []}
]